const fs = require('fs');

const data = {
  1: "• UU No. 32 Tahun 2014 tentang Kelautan — mengatur pengelolaan wilayah laut, pembangunan dan pengelolaan kelautan, pemanfaatan ruang laut, serta perlindungan lingkungan laut.\n• PP No. 21 Tahun 2021 tentang Penyelenggaraan Penataan Ruang — mengatur penyelenggaraan penataan ruang, termasuk perencanaan, pemanfaatan, dan pengendalian pemanfaatan ruang.\n• PP No. 5 Tahun 2021 tentang Penyelenggaraan Perizinan Berusaha Berbasis Risiko — mengatur perizinan berusaha berdasarkan tingkat risiko kegiatan usaha.",
  2: "• UU No. 32 Tahun 2009 tentang Perlindungan dan Pengelolaan Lingkungan Hidup — mengatur perlindungan lingkungan hidup, pencegahan pencemaran dan kerusakan lingkungan, serta pemulihan lingkungan.\n• UU No. 32 Tahun 2014 tentang Kelautan — mengatur perlindungan dan pengelolaan lingkungan laut serta pemanfaatan sumber daya kelautan secara berkelanjutan.\n• PP No. 22 Tahun 2021 tentang Penyelenggaraan Perlindungan dan Pengelolaan Lingkungan Hidup — mengatur perlindungan mutu lingkungan, pengendalian kerusakan, pemulihan lingkungan, serta pengawasan kegiatan usaha.",
  3: "• UU No. 32 Tahun 2009 tentang Perlindungan dan Pengelolaan Lingkungan Hidup — mengatur pencegahan pencemaran dan kerusakan lingkungan serta kewajiban pelaku usaha menjaga kelestarian lingkungan.\n• PP No. 22 Tahun 2021 tentang Penyelenggaraan Perlindungan dan Pengelolaan Lingkungan Hidup — mengatur pengendalian pencemaran, kerusakan lingkungan, persetujuan lingkungan, dan pengawasan kegiatan usaha.",
  4: "• UU No. 17 Tahun 2019 tentang Sumber Daya Air — mengatur pengelolaan, perlindungan, pemanfaatan, dan konservasi sumber daya air.\n• PP No. 22 Tahun 2021 tentang Penyelenggaraan Perlindungan dan Pengelolaan Lingkungan Hidup — mengatur perlindungan mutu air dan pengendalian pencemaran air.",
  5: "• Permenkes No. 2 Tahun 2023 tentang Peraturan Pelaksanaan Peraturan Pemerintah No. 66 Tahun 2014 tentang Kesehatan Lingkungan — mengatur persyaratan dan standar kesehatan lingkungan, termasuk kualitas air untuk kebutuhan masyarakat.\n• PP No. 22 Tahun 2021 tentang Penyelenggaraan Perlindungan dan Pengelolaan Lingkungan Hidup — mengatur perlindungan dan pengelolaan mutu air serta pengendalian pencemaran air.",
  6: "• PP No. 22 Tahun 2021 tentang Penyelenggaraan Perlindungan dan Pengelolaan Lingkungan Hidup — mengatur pengelolaan mutu air, pengendalian pencemaran, baku mutu air limbah, serta kewajiban pemantauan dan pengelolaan air limbah.",
  7: "• PP No. 22 Tahun 2021 tentang Penyelenggaraan Perlindungan dan Pengelolaan Lingkungan Hidup — mengatur pengelolaan limbah B3 dan non-B3, termasuk penyimpanan, pengangkutan, pemanfaatan, pengolahan, dan pembuangan limbah.",
  8: "• UU No. 18 Tahun 2008 tentang Pengelolaan Sampah — mengatur pengurangan dan penanganan sampah, termasuk pemilahan, pengumpulan, pengangkutan, pengolahan, dan pemrosesan akhir sampah.\n• PP No. 27 Tahun 2020 tentang Pengelolaan Sampah Spesifik — mengatur pengelolaan sampah yang memiliki karakteristik khusus dan memerlukan penanganan tertentu.\n• PP No. 22 Tahun 2021 tentang Penyelenggaraan Perlindungan dan Pengelolaan Lingkungan Hidup — mengatur pengelolaan limbah dan pengendalian pencemaran lingkungan.",
  9: "• Perpres No. 98 Tahun 2021 tentang Nilai Ekonomi Karbon untuk Pencapaian Target Kontribusi yang Ditetapkan Secara Nasional dan Pengendalian Emisi Gas Rumah Kaca dalam Pembangunan Nasional — mengatur mekanisme pengendalian emisi GRK dan nilai ekonomi karbon.\n• Permen LHK terkait Inventarisasi GRK — mengatur tata cara inventarisasi dan pelaporan emisi gas rumah kaca.",
  10: "• UU No. 32 Tahun 2009 tentang Perlindungan dan Pengelolaan Lingkungan Hidup — mengatur pencegahan pencemaran dan kerusakan lingkungan serta pengendalian dampak kegiatan usaha.\n• PP No. 22 Tahun 2021 tentang Penyelenggaraan Perlindungan dan Pengelolaan Lingkungan Hidup — mengatur pengendalian pencemaran dan kerusakan lingkungan.\n• Perpres No. 98 Tahun 2021 tentang Nilai Ekonomi Karbon untuk Pencapaian Target Kontribusi yang Ditetapkan Secara Nasional dan Pengendalian Emisi Gas Rumah Kaca dalam Pembangunan Nasional — mengatur pengendalian emisi GRK dan mekanisme nilai ekonomi karbon.\n• Permen LHK No. 21 Tahun 2022 tentang Penerapan Nilai Ekonomi Karbon — mengatur penerapan nilai ekonomi karbon sebagai bagian dari pengendalian emisi GRK.",
  11: "• UU No. 18 Tahun 2008 tentang Pengelolaan Sampah — mengatur pengurangan dan penanganan sampah, termasuk upaya mengurangi timbulan sampah.\n• PP No. 81 Tahun 2012 tentang Pengelolaan Sampah Rumah Tangga dan Sampah Sejenis Sampah Rumah Tangga — mengatur pengurangan dan pengelolaan sampah sejak sumbernya.\n• Permen LHK No. P.75/MENLHK/SETJEN/KUM.1/10/2019 tentang Peta Jalan Pengurangan Sampah oleh Produsen — mengatur upaya produsen mengurangi sampah dari produk dan kemasan.",
  12: "• UU No. 17 Tahun 2019 tentang Sumber Daya Air — mengatur konservasi, pendayagunaan, pengendalian daya rusak, dan pengelolaan sumber daya air.\n• PP No. 30 Tahun 2024 tentang Pengelolaan Sumber Daya Air — mengatur penyelenggaraan pengelolaan sumber daya air secara terpadu dan berkelanjutan.\n• PP No. 22 Tahun 2021 tentang Penyelenggaraan Perlindungan dan Pengelolaan Lingkungan Hidup — mengatur perlindungan mutu air dan pengendalian pencemaran air.",
  13: "• PP No. 33 Tahun 2023 tentang Konservasi Energi — mengatur konservasi energi melalui pengelolaan dan efisiensi penggunaan energi.\n• Permen ESDM tentang Manajemen Energi — mengatur penerapan sistem manajemen energi untuk meningkatkan efisiensi penggunaan energi.",
  14: "• PP No. 33 Tahun 2023 tentang Konservasi Energi — mengatur upaya penghematan dan efisiensi energi serta penerapan konservasi energi.\n• Perpres No. 22 Tahun 2017 tentang Rencana Umum Energi Nasional (RUEN) — mengatur arah dan kebijakan pengelolaan energi nasional, termasuk peningkatan efisiensi energi.",
  15: "• UU No. 30 Tahun 2007 tentang Energi — mengatur pengelolaan energi nasional, termasuk pengembangan energi baru dan terbarukan.\n• Perpres No. 112 Tahun 2022 tentang Percepatan Pengembangan Energi Terbarukan untuk Penyediaan Tenaga Listrik — mengatur percepatan pemanfaatan energi terbarukan dalam penyediaan tenaga listrik.",
  16: "• UU No. 1 Tahun 1970 tentang Keselamatan Kerja — mengatur keselamatan dan kesehatan di tempat kerja serta persyaratan lingkungan kerja yang aman dan sehat.\n• PP No. 50 Tahun 2012 tentang Penerapan Sistem Manajemen Keselamatan dan Kesehatan Kerja — mengatur penerapan sistem manajemen K3 di perusahaan.\n• Permenkes terkait sanitasi tempat kerja — mengatur persyaratan kesehatan dan sanitasi lingkungan kerja.",
  17: "• UU No. 17 Tahun 2023 tentang Kesehatan — mengatur penyelenggaraan kesehatan, termasuk upaya kesehatan lingkungan dan perlindungan kesehatan masyarakat.\n• Permenkes No. 2 Tahun 2023 tentang Peraturan Pelaksanaan Peraturan Pemerintah No. 66 Tahun 2014 tentang Kesehatan Lingkungan — mengatur standar kesehatan lingkungan, termasuk kualitas air.\n• PP No. 50 Tahun 2012 tentang Penerapan Sistem Manajemen Keselamatan dan Kesehatan Kerja — mengatur penerapan sistem K3 di lingkungan kerja.",
  18: "• UU No. 24 Tahun 2011 tentang Badan Penyelenggara Jaminan Sosial — mengatur penyelenggaraan program jaminan sosial melalui BPJS.\n• PP No. 44 Tahun 2015 tentang Penyelenggaraan Program Jaminan Kecelakaan Kerja dan Jaminan Kematian — mengatur perlindungan pekerja melalui program JKK dan JKM.\n• PP No. 82 Tahun 2019 tentang Perubahan atas PP No. 44 Tahun 2015 — mengatur perubahan ketentuan penyelenggaraan Jaminan Kecelakaan Kerja dan Jaminan Kematian.\n• UU No. 1 Tahun 1970 tentang Keselamatan Kerja — mengatur perlindungan keselamatan dan kesehatan pekerja.",
  19: "• UU No. 1 Tahun 1970 tentang Keselamatan Kerja — mengatur syarat keselamatan kerja dan perlindungan tenaga kerja dari risiko kecelakaan.\n• PP No. 50 Tahun 2012 tentang Penerapan Sistem Manajemen Keselamatan dan Kesehatan Kerja — mengatur penerapan SMK3 di perusahaan.\n• Permenaker No. 5 Tahun 2018 tentang Keselamatan dan Kesehatan Kerja Lingkungan Kerja — mengatur standar dan pengendalian faktor bahaya di lingkungan kerja.",
  20: "• UU No. 1 Tahun 1970 tentang Keselamatan Kerja — mengatur keselamatan dan kesehatan pekerja serta kondisi tempat kerja.\n• UU No. 17 Tahun 2023 tentang Kesehatan — mengatur penyelenggaraan kesehatan, termasuk kesehatan lingkungan dan kesehatan kerja.\n• PP No. 50 Tahun 2012 tentang Penerapan Sistem Manajemen Keselamatan dan Kesehatan Kerja — mengatur penerapan sistem manajemen K3.\n• Permenaker No. 5 Tahun 2018 tentang Keselamatan dan Kesehatan Kerja Lingkungan Kerja — mengatur pengendalian faktor fisik, kimia, biologi, ergonomi, dan faktor lainnya di tempat kerja.",
  21: "• UU No. 13 Tahun 2003 tentang Ketenagakerjaan sebagaimana telah diubah dengan UU No. 6 Tahun 2023 — mengatur hubungan ketenagakerjaan, termasuk pengembangan kompetensi tenaga kerja.\n• PP No. 31 Tahun 2006 tentang Sistem Pelatihan Kerja Nasional — mengatur penyelenggaraan pelatihan kerja dan peningkatan kompetensi tenaga kerja.",
  22: "• UU No. 32 Tahun 2009 tentang Perlindungan dan Pengelolaan Lingkungan Hidup — mengatur partisipasi masyarakat dalam perlindungan dan pengelolaan lingkungan hidup.\n• PP No. 22 Tahun 2021 tentang Penyelenggaraan Perlindungan dan Pengelolaan Lingkungan Hidup — mengatur persetujuan lingkungan, pelibatan masyarakat, pengawasan, dan pengendalian dampak lingkungan.",
  23: "• UU No. 13 Tahun 2003 tentang Ketenagakerjaan sebagaimana telah diubah dengan UU No. 6 Tahun 2023 — mengatur hubungan kerja, kesempatan kerja, dan perlindungan tenaga kerja.\n• PP No. 35 Tahun 2021 tentang Perjanjian Kerja Waktu Tertentu, Alih Daya, Waktu Kerja dan Waktu Istirahat, dan Pemutusan Hubungan Kerja — mengatur hubungan kerja dan ketentuan penggunaan tenaga kerja.",
  24: "• UU No. 5 Tahun 2017 tentang Pemajuan Kebudayaan — mengatur perlindungan, pengembangan, pemanfaatan, dan pembinaan kebudayaan Indonesia.\n• UU No. 20 Tahun 2008 tentang Usaha Mikro, Kecil, dan Menengah — mengatur pemberdayaan dan pengembangan UMKM serta penguatan usaha masyarakat.",
  25: "• UU No. 32 Tahun 2009 tentang Perlindungan dan Pengelolaan Lingkungan Hidup — mengatur pemanfaatan sumber daya alam secara berkelanjutan dan perlindungan lingkungan.\n• UU No. 32 Tahun 2014 tentang Kelautan — mengatur pengelolaan dan pemanfaatan sumber daya kelautan secara berkelanjutan.\n• PP No. 22 Tahun 2021 tentang Penyelenggaraan Perlindungan dan Pengelolaan Lingkungan Hidup — mengatur pengendalian dampak lingkungan dan perlindungan lingkungan.",
  26: "• UU No. 21 Tahun 2000 tentang Serikat Pekerja/Serikat Buruh — mengatur hak pekerja untuk membentuk dan menjadi anggota serikat pekerja serta perlindungan terhadap kebebasan berserikat.\n• UU No. 13 Tahun 2003 tentang Ketenagakerjaan sebagaimana telah diubah dengan UU No. 6 Tahun 2023 — mengatur hubungan industrial dan hak-hak pekerja.",
  27: "• UU No. 39 Tahun 1999 tentang Hak Asasi Manusia — mengatur penghormatan, perlindungan, dan pemenuhan hak asasi manusia tanpa diskriminasi.\n• UU No. 13 Tahun 2003 tentang Ketenagakerjaan sebagaimana telah diubah dengan UU No. 6 Tahun 2023 — mengatur perlakuan yang adil dan perlindungan hak pekerja dalam hubungan kerja.",
  28: "• UU No. 13 Tahun 2003 tentang Ketenagakerjaan sebagaimana telah diubah dengan UU No. 6 Tahun 2023 — mengatur hubungan industrial, serikat pekerja, dan perundingan bersama.\n• Permenaker terkait Perjanjian Kerja Bersama (PKB) — mengatur tata cara dan ketentuan penyusunan serta pendaftaran PKB.",
  29: "• UU No. 13 Tahun 2003 tentang Ketenagakerjaan sebagaimana telah diubah dengan UU No. 6 Tahun 2023 — mengatur perlindungan pekerja perempuan, termasuk hak cuti dan perlindungan dalam hubungan kerja.\n• UU No. 12 Tahun 2022 tentang Tindak Pidana Kekerasan Seksual — mengatur pencegahan, penanganan, perlindungan, dan pemulihan korban kekerasan seksual.\n• Permenaker terkait pekerja perempuan — mengatur perlindungan dan kondisi kerja khusus bagi pekerja perempuan.",
  30: "• UU No. 13 Tahun 2003 tentang Ketenagakerjaan sebagaimana telah diubah dengan UU No. 6 Tahun 2023 — mengatur ketentuan usia kerja, perlindungan pekerja muda, dan larangan mempekerjakan anak dalam kondisi tertentu.\n• Konvensi ILO No. 138 tentang Usia Minimum untuk Diperbolehkan Bekerja — menetapkan standar usia minimum untuk bekerja.\n• Konvensi ILO No. 182 tentang Pelarangan dan Tindakan Segera untuk Penghapusan Bentuk-Bentuk Pekerjaan Terburuk untuk Anak — mengatur penghapusan bentuk pekerjaan terburuk bagi anak.",
  31: "• UU No. 8 Tahun 2016 tentang Penyandang Disabilitas — mengatur hak penyandang disabilitas, termasuk hak memperoleh pekerjaan yang layak dan perlakuan tanpa diskriminasi.\n• PP No. 60 Tahun 2020 tentang Unit Layanan Disabilitas Bidang Ketenagakerjaan — mengatur penyediaan layanan ketenagakerjaan bagi penyandang disabilitas.",
  32: "• UU No. 13 Tahun 2003 tentang Ketenagakerjaan sebagaimana telah diubah dengan UU No. 6 Tahun 2023 — mengatur hubungan kerja dan perlindungan hak pekerja.\n• Konvensi ILO No. 29 tentang Kerja Paksa — mengatur penghapusan kerja paksa dalam segala bentuk.\n• Konvensi ILO No. 105 tentang Penghapusan Kerja Paksa — mengatur penghapusan kerja paksa sebagai sarana pemaksaan atau hukuman.",
  33: "• UU No. 13 Tahun 2003 tentang Ketenagakerjaan sebagaimana telah diubah dengan UU No. 6 Tahun 2023 — mengatur batas usia kerja dan perlindungan anak dari pekerjaan yang membahayakan.\n• Konvensi ILO No. 138 tentang Usia Minimum untuk Diperbolehkan Bekerja — menetapkan usia minimum untuk bekerja.\n• Konvensi ILO No. 182 tentang Pelarangan dan Tindakan Segera untuk Penghapusan Bentuk-Bentuk Pekerjaan Terburuk untuk Anak — mengatur penghapusan pekerjaan terburuk bagi anak.",
  34: "• PP No. 36 Tahun 2021 tentang Pengupahan — mengatur kebijakan pengupahan, struktur dan skala upah, upah minimum, perlindungan upah, dan pembayaran upah.\n• UU No. 13 Tahun 2003 tentang Ketenagakerjaan sebagaimana telah diubah dengan UU No. 6 Tahun 2023 — mengatur hak pekerja atas pengupahan dan perlindungan dalam hubungan kerja.",
  35: "• UU No. 13 Tahun 2003 tentang Ketenagakerjaan sebagaimana telah diubah dengan UU No. 6 Tahun 2023 — mengatur hubungan kerja dan perlindungan hak pekerja.\n• PP No. 35 Tahun 2021 tentang Perjanjian Kerja Waktu Tertentu, Alih Daya, Waktu Kerja dan Waktu Istirahat, dan Pemutusan Hubungan Kerja — mengatur PKWT, alih daya, waktu kerja, waktu istirahat, lembur, dan PHK.",
  36: "• UU No. 13 Tahun 2003 tentang Ketenagakerjaan sebagaimana telah diubah dengan UU No. 6 Tahun 2023 — mengatur hubungan kerja dan ketentuan perjanjian kerja antara pekerja dan pengusaha.\n• PP No. 35 Tahun 2021 tentang Perjanjian Kerja Waktu Tertentu, Alih Daya, Waktu Kerja dan Waktu Istirahat, dan Pemutusan Hubungan Kerja — mengatur ketentuan PKWT dan hubungan kerja.",
  37: "• PP No. 36 Tahun 2021 tentang Pengupahan — mengatur pembayaran upah, struktur dan skala upah, perlindungan upah, serta ketentuan pembayaran upah.\n• UU No. 13 Tahun 2003 tentang Ketenagakerjaan sebagaimana telah diubah dengan UU No. 6 Tahun 2023 — mengatur hak pekerja atas upah dan perlindungan pengupahan.",
  38: "• UU No. 13 Tahun 2003 tentang Ketenagakerjaan sebagaimana telah diubah dengan UU No. 6 Tahun 2023 — mengatur waktu kerja, waktu istirahat, kerja lembur, dan hak pekerja.\n• PP No. 35 Tahun 2021 tentang Perjanjian Kerja Waktu Tertentu, Alih Daya, Waktu Kerja dan Waktu Istirahat, dan Pemutusan Hubungan Kerja — mengatur waktu kerja, waktu istirahat, kerja lembur, dan upah lembur.\n• Kepmenaker No. 102/MEN/VI/2004 tentang Waktu Kerja Lembur dan Upah Kerja Lembur — mengatur ketentuan pelaksanaan kerja lembur dan pembayaran upah lembur.",
  39: "• UU No. 13 Tahun 2003 tentang Ketenagakerjaan sebagaimana telah diubah dengan UU No. 6 Tahun 2023 — mengatur hak pekerja atas cuti dan perlindungan pekerja perempuan.\n• UU No. 17 Tahun 2023 tentang Kesehatan — mengatur penyelenggaraan kesehatan, termasuk perlindungan kesehatan ibu dan anak.\n• PP No. 35 Tahun 2021 tentang Perjanjian Kerja Waktu Tertentu, Alih Daya, Waktu Kerja dan Waktu Istirahat, dan Pemutusan Hubungan Kerja — mengatur waktu kerja dan waktu istirahat pekerja.",
  40: "• UU No. 13 Tahun 2003 tentang Ketenagakerjaan sebagaimana telah diubah dengan UU No. 6 Tahun 2023 — mengatur hak pekerja ketika hubungan kerja berakhir, termasuk hak terkait masa kerja dan pensiun.\n• UU No. 24 Tahun 2011 tentang Badan Penyelenggara Jaminan Sosial — mengatur penyelenggaraan jaminan sosial bagi pekerja.\n• PP No. 45 Tahun 2015 tentang Penyelenggaraan Program Jaminan Pensiun — mengatur penyelenggaraan program jaminan pensiun bagi pekerja.\n• PP No. 46 Tahun 2015 tentang Penyelenggaraan Program Jaminan Hari Tua — mengatur penyelenggaraan program jaminan hari tua.",
  41: "• UU No. 13 Tahun 2003 tentang Ketenagakerjaan sebagaimana telah diubah dengan UU No. 6 Tahun 2023 — mengatur hak pekerja atas pengupahan dan perlindungan tenaga kerja.\n• PP No. 36 Tahun 2021 tentang Pengupahan — mengatur upah minimum, struktur dan skala upah, serta perlindungan upah.",
  42: "• PP No. 36 Tahun 2021 tentang Pengupahan — mengatur kebijakan pengupahan, struktur dan skala upah, upah minimum, dan perlindungan upah.\n• UU No. 13 Tahun 2003 tentang Ketenagakerjaan sebagaimana telah diubah dengan UU No. 6 Tahun 2023 — mengatur hak pekerja atas penghasilan yang memenuhi kebutuhan hidup yang layak.",
  43: "• UU No. 40 Tahun 2004 tentang Sistem Jaminan Sosial Nasional — mengatur penyelenggaraan sistem jaminan sosial nasional bagi masyarakat dan pekerja.\n• UU No. 24 Tahun 2011 tentang Badan Penyelenggara Jaminan Sosial — mengatur pembentukan dan penyelenggaraan BPJS.\n• PP No. 44 Tahun 2015 tentang Penyelenggaraan Program Jaminan Kecelakaan Kerja dan Jaminan Kematian — mengatur perlindungan pekerja melalui program JKK dan JKM.\n• PP No. 45 Tahun 2015 tentang Penyelenggaraan Program Jaminan Pensiun — mengatur program jaminan pensiun pekerja.\n• PP No. 46 Tahun 2015 tentang Penyelenggaraan Program Jaminan Hari Tua — mengatur program jaminan hari tua pekerja.\n• PP No. 37 Tahun 2021 tentang Penyelenggaraan Program Jaminan Kehilangan Pekerjaan — mengatur perlindungan bagi pekerja yang mengalami kehilangan pekerjaan.",
  44: "• UU No. 6 Tahun 1983 tentang Ketentuan Umum dan Tata Cara Perpajakan sebagaimana telah beberapa kali diubah, terakhir dengan UU No. 7 Tahun 2021 tentang Harmonisasi Peraturan Perpajakan — mengatur ketentuan umum perpajakan, pendaftaran wajib pajak, pelaporan SPT, pembayaran, serta administrasi perpajakan.",
  45: "• UU No. 1 Tahun 2022 tentang Hubungan Keuangan antara Pemerintah Pusat dan Pemerintahan Daerah — mengatur hubungan keuangan pusat dan daerah, termasuk pajak daerah dan retribusi daerah serta pengelolaan pendapatan daerah.",
  46: "• KUH Perdata — mengatur hubungan hukum perdata, termasuk perjanjian, hak dan kewajiban para pihak, serta akibat hukum dari suatu perjanjian.\n• UU No. 8 Tahun 1999 tentang Perlindungan Konsumen — mengatur hak dan kewajiban konsumen serta pelaku usaha dan perlindungan konsumen.\n• UU No. 7 Tahun 2014 tentang Perdagangan — mengatur kegiatan perdagangan, hubungan pelaku usaha, serta ketentuan perdagangan barang dan jasa.",
  47: "• UU No. 18 Tahun 2008 tentang Pengelolaan Sampah — mengatur pengurangan dan penanganan sampah, termasuk pemanfaatan kembali dan daur ulang.\n• PP No. 27 Tahun 2020 tentang Pengelolaan Sampah Spesifik — mengatur pengelolaan sampah yang memiliki karakteristik khusus.\n• PP No. 22 Tahun 2021 tentang Penyelenggaraan Perlindungan dan Pengelolaan Lingkungan Hidup — mengatur pengelolaan limbah dan pengendalian dampak lingkungan.",
  48: "• UU No. 11 Tahun 2019 tentang Sistem Nasional Ilmu Pengetahuan dan Teknologi — mengatur penyelenggaraan ilmu pengetahuan dan teknologi, penelitian, pengembangan, inovasi, serta pemanfaatan hasil teknologi untuk pembangunan.",
  49: "• UU No. 20 Tahun 2008 tentang Usaha Mikro, Kecil, dan Menengah — mengatur pemberdayaan, pengembangan, perlindungan, dan kemitraan UMKM.\n• PP No. 7 Tahun 2021 tentang Kemudahan, Pelindungan, dan Pemberdayaan Koperasi dan Usaha Mikro, Kecil, dan Menengah — mengatur kemudahan berusaha, perlindungan, pemberdayaan, pembinaan, serta pengembangan UMKM.",
  50: "• UU No. 27 Tahun 2022 tentang Pelindungan Data Pribadi — mengatur pelindungan data pribadi, hak subjek data, kewajiban pengendali/pemroses data, serta keamanan dan pemrosesan data pribadi.\n• UU No. 11 Tahun 2008 tentang Informasi dan Transaksi Elektronik sebagaimana telah diubah dengan UU No. 1 Tahun 2024 — mengatur informasi elektronik, transaksi elektronik, sistem elektronik, serta aspek hukum pemanfaatan teknologi informasi.\n• PP No. 71 Tahun 2019 tentang Penyelenggaraan Sistem dan Transaksi Elektronik — mengatur penyelenggaraan sistem elektronik, kewajiban penyelenggara sistem elektronik, keamanan sistem, dan transaksi elektronik."
};

let fileContent = fs.readFileSync('Backend/database/seeders/IndicatorAuditDataSeeder.php', 'utf8');

for (let i = 1; i <= 50; i++) {
  // Find the block for the current indicator index
  const regex = new RegExp(`(\\s+${i}\\s*=>\\s*\\[.*?'regulation'\\s*=>\\s*)'.*?'`, 's');
  // Escape single quotes and replace newlines with actual PHP \n characters if needed. 
  // Actually, we can use a double quoted string or heredoc, or just escape single quotes.
  let replacementText = data[i].replace(/'/g, "\\'");
  
  // To support newlines in PHP string without breaking formatting, we can just use double quotes
  // and \n literal, but since we are modifying PHP code, let's inject a double quoted string.
  // Wait, if we use double quotes, we must escape $. There are no $ in the text.
  let replacementStr = `"${replacementText.replace(/\\n/g, '\\n')}"`;
  
  fileContent = fileContent.replace(regex, `$1${replacementStr}`);
}

fs.writeFileSync('Backend/database/seeders/IndicatorAuditDataSeeder.php', fileContent);
console.log('Seeder updated successfully.');
